# ------------------------------------------------------------------------------
# Firebase Emulator for Tests local and CI
# ------------------------------------------------------------------------------

version: "3.3"

services:

  # -------------------------------------
  # Firebase Eumulator
  # -------------------------------------

  emulator:
    image: ehealthafrica/firebase-emulator:latest
    build: .
    volumes:
      - ./hosted.json:/app/override.json:rw
      - firebase:/app/fb/functions:rw
      - firebase:/app/fb/public:rw
      - firebase:/home/docker/.cache/firebase/emulators:rw
      - firebase:/app/fb:rw
    environment:
      FIREBASE_TOKEN: ${FIREBASE_TOKEN}
      FIREBASE_PROJECT: ${FIREBASE_PROJECT}
    ports:
      - 5001:5001
      - 9000:9000
      - 8080:8080
      - 8085:8085
      - 5000:5000
      - 4000:4000
    entrypoint:
      ["/app/entrypoint.sh"] 

volumes:
  firebase:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: "${PWD}/data"